### ISSUE TITLE
broken example

### ISSUE THREAD

**Issue by fabianp** [openopt/chop#36]
I'm getting the following error on examples/adversarial_robustness/plot_visualizing_adversarial_attacks.py :

```
Files already downloaded and verified
L2 norm constraint.
GroupL1 constraint.
Traceback (most recent call last):
  File "plot_visualizing_adversarial_attacks.py", line 94, in <module>
    _, delta_group = adversary_group.perturb(data, target, model, criterion,
  File "/home/pedregosa/dev/chop/chop/adversary.py", line 93, in perturb
    sol = self.method(loss, delta0, step=step, max_iter=max_iter, 
  File "/home/pedregosa/dev/chop/chop/optim.py", line 394, in minimize_frank_wolfe
    raise ValueError("step must be a float or 'sublinear'.")
ValueError: step must be a float or 'sublinear'.
```

**Comment by GeoffNN** [comment]
Fixed
